# This is a basic workflow that is manually triggered

name: Manual update Jenkins

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'update Jenkins to the latest version'
        # Default value if no value is explicitly provided
        default: 'latest'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: update Jenkins
      env: # Or as an environment variable
        REGISTRY_USER_NAME: ${{ secrets.REGISTRY_USER_NAME }},
        REGISTRY_USER_PSW: ${{ secrets.REGISTRY_USER_PSW }}
      run: | 
        sh ./build_and_run_jenkins.sh
      
